apiVersion: apps/v1 # For versions before 1.9.0 use apps/v1beta2
kind: Deployment    
metadata:   # Data that helps  uniquely identify the object (using name, UID and namespace)          
  name: peerpulse-frontend-deployment
spec:  # What state you desire for the object              
  selector:  # The selector field defines how the deployment finds which pod to manage       
    matchLabels:
      app: peerpulse-frontend-deployment
  replicas: 1  # Tells the deployment to run 3 pods matching the template      
  template:
    metadata:
      labels:  # Labels are used as indentifying attributes for objects such as pods and replication controller.      
        app: peerpulse-frontend-deployment
    spec:
      containers:
        - name: peerpulse-frontend-deployment
          image: anarghya15/peerpulse-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
